#!/bin/bash
// TODO: Update path of your Java binary if necessary

JAVA_MAIN="CommitMsgHook"

echo "Compiling $JAVA_MAIN.java..."
javac "$JAVA_MAIN.java"
if [ $? -ne 0 ]; then
    echo "Commit aborted: Java compilation failed."
    exit 1
fi

echo "Running $JAVA_MAIN..."
java "$JAVA_MAIN"
if [ $? -ne 0 ]; then
    echo "Commit aborted: Java program failed."
    exit 1
fi

echo "Java program ran successfully. Proceeding with commit."
exit 0